config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'signup'
  },
  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: "home#index"
  resources :loan, only: [:index, :create, :update]
  get 'profile', to: "users#profile"

  namespace :admin do
    # root 'home#index'
    get 'transactions_history', to: 'home#transactions_history'
    get 'loan_requests', to: "home#loan_requests"
    get 'loan_history', to: "home#loan_history"
  end
  get "*path", to: "home#index"
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < ApplicationController
    before_action :authenticate_user!

    def index
      @wallet = current_user.wallet
    end
    
    def loan_requests
      @loan_requests = Loan.all.requested
      render json: LoanSerializer.new(@loan_requests).serializable_hash, status: :ok
    end

    def loan_history
      @loans = Loan.all
      render json: LoanSerializer.new(@loans).serializable_hash, status: :ok
    end
  
    def transactions_history
      @transactions = current_user.wallet_transactions
      render json: WalletTransactionSerializer.new(@transactions).serializable_hash, status: :ok
    end
    private

    def ensure_admin
      unless current_user.admin?
        redirect_to root_path, alert: 'You are not authorized to access this page.'
      end
    end  
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # user = current_user&.admin?
    # case user
    # when true
    #   redirect_to admin_home_index_path
    # when false
    #   redirect_to user_dashboard_index_path
    # else
    #   redirect_to root_path
    # end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/home/index.html.erb
<% if user_signed_in? %> 
 <div> Welcome <%= current_user.email %> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>

<h1>Welcome, <%= current_user.first_name %>!</h1>

<% if @wallet %>
  <p>Your Wallet Balance: <%= number_to_currency(@wallet.balance) %></p>
<% else %>
  <p>Your wallet balance is currently unavailable.</p>
<% end %>

<%= link_to "All Loan Request", admin_loan_requests_path %> 
<%= link_to "All Loan History", admin_loan_history_path %> 

app/views/admin/home/loan_history.html.erb
<div class="admin-home-container">
  <h1>All Loans</h1>

  <table>
    <thead>
      <tr>
        <th>Amount</th>
        <th>Interest Rate</th>
        <th>Total Loan Amount</th>
        <th>State</th>
        <th>Paid</th>
        <th>User</th>
      </tr>
    </thead>
    <tbody>
      <% @loans.each do |loan| %>
        <tr>
          <td><%= number_to_currency(loan.amount) %></td>
          <td><%= loan.interest_rate %>%</td>
          <td><%= number_to_currency(loan.total_loan_amount) %></td>
          <td><%= loan.state.humanize %></td>
          <td><%= loan.paid? ? "Yes" : "No" %></td>
          <td><%= loan.user.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h1>All Transactions</h1>

  <table>
    <thead>
      <tr>
        <th>Amount</th>
        <th>Transaction Type</th>
        <th>User</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= number_to_currency(transaction.amount) %></td>
          <td><%= transaction.transaction_type.humanize %></td>
          <td><%= transaction.user.email %></td>
          <td><%= transaction.created_at.strftime("%Y-%m-%d") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/home/loan_requests.html.erb
<div class="loans-container">
  <h1>Your Loans</h1>

  <table>
    <thead>
      <tr>
        <th>Amount</th>
        <th>State</th>
        <th>Created At</th>
        <th>User name</th>
        <th>Not approved</th>
      </tr>
    </thead>
    <tbody>
      <% @loan_requests.each do |request| %>
        <tr>
          <td><%= number_to_currency(request.amount) %></td>
          <td><%= request.state.humanize %></td>
          <td><%= request.created_at.strftime("%Y-%m-%d") %></td>
          <td><%= request.user.first_name%></td>
          <td>
            <% if request.state == "requested" %>
              <%= link_to "Approve/reject", edit_loan_path(request), method: :get, class: "btn btn-success" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>