config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'signup'
  },
  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: "home#index"
  resources :loan, only: [:index, :create, :update]
  get 'profile', to: "users#profile"

  namespace :admin do
    # root 'home#index'
    get 'transactions_history', to: 'home#transactions_history'
    get 'loan_requests', to: "home#loan_requests"
    get 'loan_history', to: "home#loan_history"
  end
  get "*path", to: "home#index"
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  has_many :wallet_transactions


  enum state: { requested: 0, approved: 1, open: 2, closed: 3, rejected: 4 }

  validates :amount, presence: true, numericality: { greater_than_0: true }
end

app/controllers/loan_controller.rb
class LoanController < ApplicationController
  include Loanable
  before_action :authenticate_user!  # Ensure user is logged in
  before_action :set_loan, only: [ :update]
  after_action :check_state, only: [ :update]

  def index
    @loans = current_user.loans
    render json: LoanSerializer.new(@loans).serializable_hash, status: :ok
  end


  def create
    @user = current_user
    @loan = @user.loans.new(loan_params)
    @loan.user = current_user  # Assign loan to the current user
  
    if @loan.save
      render json: {message: "Loan request submitted successfully!"}, status: :created
    else
      render json: {message: "User couldn't be created successfully. #{@loan.errors.full_messages.to_sentence}"}, status: :unprocessable_entity
    end
  end

  def update
    if @loan.update(loan_params)
      render json: {message: "Loan updated successfully!"}, status: :ok
    else
      render json: {message: "User couldn't be created successfully. #{@loan.errors.full_messages.to_sentence}"}, status: :unprocessable_entity
    end
  end

  private

  def loan_params 
    params.require(:loan).permit(:amount, :state, :interest_rate)
  end
end

app/helpers/loan_helper.rb
module LoanHelper
end

app/views/loan/edit.html.erb
<h1>Request Loan</h1>

<%= form_for @loan, url: loan_path, method: :patch do |f| %>

  <div class="field">
    <%= f.label :amount, "Loan Amount:" %><br />
    <%= number_to_currency(@loan.amount, disabled: true) %>
  </div>

  <div class="field">
    <%= f.label :interest_rate, "Interest Rate (%):" %><br />
    <%= f.number_field :interest_rate, min: 0.01, step: 0.01, placeholder: "Enter interest rate", class: "form-control" %>
  </div>

  <div class="field">
    <%= f.radio_button :state, 'approved' %> 
    <%= f.label :state, 'approved' %>
    <%= f.radio_button :state, 'rejected' %>
    <%= f.label :state, 'reject' %>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/loan/index.html.erb
<div class="loans-container">
  <h1>Your Loans</h1>

  <table>
    <thead>
      <tr>
        <th>Amount</th>
        <th>Interest Rate</th>
        <th>Total Loan Amount</th>
        <th>State</th>
        <th>Paid</th>
        <th>Created At</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @loans.each do |loan| %>
        <tr>
          <td><%= number_to_currency(loan.amount) %></td>
          <td><%= loan.interest_rate %>%</td>
          <td><%= number_to_currency(loan.total_loan_amount) %></td>
          <td><%= loan.state.humanize %></td>
          <td><%= loan.paid? ? "Yes" : "No" %></td>
          <td><%= loan.created_at.strftime("%Y-%m-%d") %></td>
          <td>
            <% if loan.state == "approved" %>
              <%= form_for loan, url: loan_path(loan), method: :patch do |f| %>
                <div class="form-group">
                  <%= f.label :interest_rate, "Interest Rate (%):" %>
                  <%= f.text_field :interest_rate, readonly: true, value: loan.interest_rate %>
                </div>
                <%= f.radio_button :state, 'open' %>
                <%= f.label :state, 'Confirm' %>
                <%= f.radio_button :state, 'rejected' %>
                <%= f.label :state, 'Reject' %>
                <%= f.submit "Confirm", class: "btn btn-primary" %>
              <% end %>
            <% elsif loan.state == "open" %>
              <%= form_for loan, url: loan_path(loan), method: :patch do |f| %>
                <%= f.hidden_field :state, value: "closed" %>
                <%= f.submit "Pay", class: "btn btn-primary" %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h1>Transaction History</h1>
  <table>
    <thead>
      <tr>
        <th>Amount</th>
        <th>Transaction Type</th>
        <th>Loan ID</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= number_to_currency(transaction.amount) %></td>
          <td><%= transaction.transaction_type.humanize %></td>
          <td><%= transaction.loan_id %></td>
          <td><%= transaction.created_at.strftime("%Y-%m-%d") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/loan/new.html.erb
<h1>Request Loan</h1>

<%= form_for @loan, url: '/loan', method: :post do |f| %>

  <div class="field">
    <%= f.label :amount, "Loan Amount:" %><br />
    <%= f.number_field :amount, min: 100, placeholder: "Enter your loan amount" %>
    <%= f.hidden_field :state,value: "requested" %>
  </div>

  <%= f.submit "Submit Loan Request" %>
<% end %>